[versions]

# /!\ Koin in gradle.properties /!\

# Core
kotlin = "1.9.21"
koin = "3.5.3"
ksp = "1.9.21-1.0.16"
publish = "2.0.0-rc-1"
dokka = "1.9.10"

[libraries]
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
ksp-api = {module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "ksp"}

[plugins]
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
nexusPublish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "publish" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }