name: Build & Test

on:
  push:
    branches:
      - '*'
      - '*/*'
  
  pull_request:
    branches:    
      - '*'

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    runs-on: macos-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11
    
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Install Compiler
        run: cd compiler && ./install.sh

      - name: Run Sandbox Test
        run: cd sandbox && ./test.sh


